### ISSUE TITLE
Version Tagging -- Conflict with com.zend.php.productivity.feature.group

### ISSUE THREAD

**Issue by arstropica** [pulse00/smartypdt#5]
Are there tags and/or releases for previous versions of the plugin? If not, could you do this so that eclipse has more possibilities for workarounds when encountering  dependency issues? 

Per the below log, v. 0.10.0.2* seems to have a conflict with com.zend.php.productivity.feature.group.
Thanks.

!ENTRY org.eclipse.equinox.p2.operations 4 0 2018-02-28 14:06:46.286
!MESSAGE Operation details
!SUBENTRY 1 org.eclipse.equinox.p2.director 4 10054 2018-02-28 14:06:46.286
!MESSAGE Cannot complete the install because of a conflicting dependency.
!SUBENTRY 2 org.eclipse.equinox.p2.director 4 0 2018-02-28 14:06:46.286
!MESSAGE Software being installed: Smarty Feature 0.10.0.201707132003 (org.eclipse.php.smarty_feature.feature.group 0.10.0.201707132003)
!SUBENTRY 2 org.eclipse.equinox.p2.director 4 0 2018-02-28 14:06:46.286
!MESSAGE Software currently installed: Zend Studio 13.6.1.v20170410-20170623-1730-697 (com.zend.php.ide 13.6.1.v20170410-20170623-1730-697)
!SUBENTRY 2 org.eclipse.equinox.p2.director 4 1 2018-02-28 14:06:46.286
!MESSAGE Only one of the following can be installed at once: 
!SUBENTRY 3 org.eclipse.equinox.p2.director 4 0 2018-02-28 14:06:46.286
!MESSAGE PDT Smart Importer Plug-in 5.2.0.201712021751 (org.eclipse.php.ui.importer 5.2.0.201712021751)
!SUBENTRY 3 org.eclipse.equinox.p2.director 4 0 2018-02-28 14:06:46.286
!MESSAGE PDT Smart Importer Plug-in 4.3.0.201703131616 (org.eclipse.php.ui.importer 4.3.0.201703131616)
!SUBENTRY 3 org.eclipse.equinox.p2.director 4 0 2018-02-28 14:06:46.286
!MESSAGE PDT Smart Importer Plug-in 4.1.0.201609140517 (org.eclipse.php.ui.importer 4.1.0.201609140517)
!SUBENTRY 3 org.eclipse.equinox.p2.director 4 0 2018-02-28 14:06:46.286
!MESSAGE PDT Smart Importer Plug-in 4.2.0.201611142355 (org.eclipse.php.ui.importer 4.2.0.201611142355)
!SUBENTRY 3 org.eclipse.equinox.p2.director 4 0 2018-02-28 14:06:46.286
!MESSAGE PDT Smart Importer Plug-in 4.3.0.201703072355 (org.eclipse.php.ui.importer 4.3.0.201703072355)
!SUBENTRY 3 org.eclipse.equinox.p2.director 4 0 2018-02-28 14:06:46.286
!MESSAGE PDT Smart Importer Plug-in 4.3.2.201706231408 (org.eclipse.php.ui.importer 4.3.2.201706231408)
!SUBENTRY 3 org.eclipse.equinox.p2.director 4 0 2018-02-28 14:06:46.286
!MESSAGE PDT Smart Importer Plug-in 4.0.0.201606081033 (org.eclipse.php.ui.importer 4.0.0.201606081033)
!SUBENTRY 2 org.eclipse.equinox.p2.director 4 1 2018-02-28 14:06:46.286
!MESSAGE Cannot satisfy dependency:
!SUBENTRY 3 org.eclipse.equinox.p2.director 4 0 2018-02-28 14:06:46.286
!MESSAGE From: Zend Studio 13.6.1.v20170410-20170623-1730-697 (com.zend.php.ide 13.6.1.v20170410-20170623-1730-697)
!SUBENTRY 3 org.eclipse.equinox.p2.director 4 0 2018-02-28 14:06:46.286
!MESSAGE To: com.zend.php.productivity.feature.group [13.6.1.v20170410-20170623-1730-697]
!SUBENTRY 2 org.eclipse.equinox.p2.director 4 1 2018-02-28 14:06:46.286
!MESSAGE Cannot satisfy dependency:
!SUBENTRY 3 org.eclipse.equinox.p2.director 4 0 2018-02-28 14:06:46.286
!MESSAGE From: Zend Studio Feature 13.6.1.v20170410-20170623-1730-697 (com.zend.php.productivity.feature.group 13.6.1.v20170410-20170623-1730-697)
!SUBENTRY 3 org.eclipse.equinox.p2.director 4 0 2018-02-28 14:06:46.286
!MESSAGE To: org.eclipse.php.importer.feature.group 0.0.0
!SUBENTRY 2 org.eclipse.equinox.p2.director 4 1 2018-02-28 14:06:46.286
!MESSAGE Cannot satisfy dependency:
!SUBENTRY 3 org.eclipse.equinox.p2.director 4 0 2018-02-28 14:06:46.287
!MESSAGE From: PHP Development Tools (PDT) 5.2.0.201712021751 (org.eclipse.php.feature.group 5.2.0.201712021751)
!SUBENTRY 3 org.eclipse.equinox.p2.director 4 0 2018-02-28 14:06:46.287
!MESSAGE To: org.eclipse.php.ui.importer [5.2.0.201712021751]
!SUBENTRY 2 org.eclipse.equinox.p2.director 4 1 2018-02-28 14:06:46.287
!MESSAGE Cannot satisfy dependency:
!SUBENTRY 3 org.eclipse.equinox.p2.director 4 0 2018-02-28 14:06:46.287
!MESSAGE From: PHP Development Tools (PDT) Smart Import 4.0.0.201606081033 (org.eclipse.php.importer.feature.group 4.0.0.201606081033)
!SUBENTRY 3 org.eclipse.equinox.p2.director 4 0 2018-02-28 14:06:46.287
!MESSAGE To: org.eclipse.php.ui.importer [4.0.0.201606081033]
!SUBENTRY 2 org.eclipse.equinox.p2.director 4 1 2018-02-28 14:06:46.287
!MESSAGE Cannot satisfy dependency:
!SUBENTRY 3 org.eclipse.equinox.p2.director 4 0 2018-02-28 14:06:46.287
!MESSAGE From: PHP Development Tools (PDT) Smart Import 4.1.0.201609140517 (org.eclipse.php.importer.feature.group 4.1.0.201609140517)
!SUBENTRY 3 org.eclipse.equinox.p2.director 4 0 2018-02-28 14:06:46.287
!MESSAGE To: org.eclipse.php.ui.importer [4.1.0.201609140517]
!SUBENTRY 2 org.eclipse.equinox.p2.director 4 1 2018-02-28 14:06:46.287
!MESSAGE Cannot satisfy dependency:
!SUBENTRY 3 org.eclipse.equinox.p2.director 4 0 2018-02-28 14:06:46.287
!MESSAGE From: PHP Development Tools (PDT) Smart Import 4.2.0.201611142355 (org.eclipse.php.importer.feature.group 4.2.0.201611142355)
!SUBENTRY 3 org.eclipse.equinox.p2.director 4 0 2018-02-28 14:06:46.287
!MESSAGE To: org.eclipse.php.ui.importer [4.2.0.201611142355]
!SUBENTRY 2 org.eclipse.equinox.p2.director 4 1 2018-02-28 14:06:46.287
!MESSAGE Cannot satisfy dependency:
!SUBENTRY 3 org.eclipse.equinox.p2.director 4 0 2018-02-28 14:06:46.287
!MESSAGE From: PHP Development Tools (PDT) Smart Import 4.3.0.201703072355 (org.eclipse.php.importer.feature.group 4.3.0.201703072355)
!SUBENTRY 3 org.eclipse.equinox.p2.director 4 0 2018-02-28 14:06:46.287
!MESSAGE To: org.eclipse.php.ui.importer [4.3.0.201703072355]
!SUBENTRY 2 org.eclipse.equinox.p2.director 4 1 2018-02-28 14:06:46.287
!MESSAGE Cannot satisfy dependency:
!SUBENTRY 3 org.eclipse.equinox.p2.director 4 0 2018-02-28 14:06:46.287
!MESSAGE From: PHP Development Tools (PDT) Smart Import 4.3.0.201703131616 (org.eclipse.php.importer.feature.group 4.3.0.201703131616)
!SUBENTRY 3 org.eclipse.equinox.p2.director 4 0 2018-02-28 14:06:46.287
!MESSAGE To: org.eclipse.php.ui.importer [4.3.0.201703131616]
!SUBENTRY 2 org.eclipse.equinox.p2.director 4 1 2018-02-28 14:06:46.287
!MESSAGE Cannot satisfy dependency:
!SUBENTRY 3 org.eclipse.equinox.p2.director 4 0 2018-02-28 14:06:46.287
!MESSAGE From: PHP Development Tools (PDT) Smart Import 4.3.2.201706231408 (org.eclipse.php.importer.feature.group 4.3.2.201706231408)
!SUBENTRY 3 org.eclipse.equinox.p2.director 4 0 2018-02-28 14:06:46.287
!MESSAGE To: org.eclipse.php.ui.importer [4.3.2.201706231408]
!SUBENTRY 2 org.eclipse.equinox.p2.director 4 1 2018-02-28 14:06:46.287
!MESSAGE Cannot satisfy dependency:
!SUBENTRY 3 org.eclipse.equinox.p2.director 4 0 2018-02-28 14:06:46.287
!MESSAGE From: Smarty Feature 0.10.0.201707132003 (org.eclipse.php.smarty_feature.feature.group 0.10.0.201707132003)
!SUBENTRY 3 org.eclipse.equinox.p2.director 4 0 2018-02-28 14:06:46.287
!MESSAGE To: org.eclipse.php.feature.group 5.0.0

**Comment by zulus** [comment]
This is a fork that from time to time is synced with latest PDT, we haven't tags from previous versions.

Compatible with Zend Studio should be build from here: http://dl.bintray.com/pulse00/pdt-extensions/release/4.6.3/

**Comment by arstropica** [comment]
Perfect. v.0.9.3 installed without a hitch.

Thanks!
